### ISSUE TITLE
map displays on wiki outside its box, JavaScript errors

### ISSUE THREAD

**Issue by skierpage** [openstreetmap/mediawiki-skins-osmf#1]
I visit http://wiki.openstreetmap.org/wiki/South_Bay_(SF),_California in chromium and Firefox Nightly (49.0a1 (2016-05-30)) running on my Kubuntu desktop, and no map appears "above the fold" in the space for the map unless I resize my browser really wide. instead the map displays partway through the first paragraph, obscuring several paragraphs and headings.

In the Firefox browser console I see an error:
```
Error: OpenLayers.Control.Button is not a constructor
   slippymap_init()      South_Bay_(SF),_California:87:1096 [in the page HTML]
  <anonymous>
```
also some warnings about deprecated usage. I'll file a separate bug for these. Here's the glitch in chromium:
![openstreetmap_wiki_bug](https://cloud.githubusercontent.com/assets/1303668/15727226/fc19f530-2809-11e6-941c-9d232e177b9d.png)

**Comment by tomhughes** [comment]
What does an issue in the main wiki have to do with the skin used in the OSMF wiki though? I'm guessing nothing at all...

Most likely this issue is in the SlippyMap mediawiki extension that we have installed. IT certainly isn't anything to do with this repository though.

**Comment by skierpage** [comment]
Sorry, this seemed to be the closest thing to report bugs with the wiki. http://wiki.openstreetmap.org/wiki/Reporting_bugs was no help. I since found http://wiki.openstreetmap.org/wiki/Report_a_problem_article
