### ISSUE TITLE
ResourceLoader deprecation warnings and JS error on wiki

### ISSUE THREAD

**Issue by skierpage** [openstreetmap/mediawiki-skins-osmf#2]
Visiting http://wiki.openstreetmap.org/wiki/South_Bay_(SF),_California, the Firefox browser console reports warnings
```
Use of "addOnloadHook" is deprecated. Use jQuery instead.load.php:156:550
Use of "wgNamespaceNumber" is deprecated. Use mw.config instead.load.php:156:550
Use of "addOnloadHook" is deprecated. Use jQuery instead.load.php:156:550
```
The page https://www.mediawiki.org/wiki/ResourceLoader/Migration_guide_(users) has advice for updating to avoid these deprecation warnings.

The browser console also reports the error:
```
TypeError: OpenLayers.Control.Button is not a constructor
```
in Debug mode (append ```?debug=1``` to the URL), the call stack is
slippymap_init()  South_Bay_(SF),_California:186
<anonymous> South_Bay_(SF),_California:186
openRemotePrompt() nsPrompter.js:491
ModalPrompter.prototype.openPrompt() nsPrompter.js:526
ModalPrompter.prototype.alert() nsPrompter.js:602
nG() /calendar/_/scs/calendar-static/_/js/k=calendar.cal.en.HHbEiX2Uk30.O/m=extras/rt=j/rs=ANwU0p7DLDvbBf
sya()   /calendar/_/scs/calendar-static/_/js/k=calendar.cal.en.HHbEiX2Uk30.O/m=extras/rt=j/rs=ANwU0p7DLDvbBf
uya()  /calendar/_/scs/calendar-static/_/js/k=calendar.cal.en.HHbEiX2Uk30.O/m=extras/rt=j/rs=ANwU0p7DLDvbBf
tya()  /calendar/_/scs/calendar-static/_/js/k=calendar.cal.en.HHbEiX2Uk30.O/m=extras/rt=j/rs=ANwU0p7DLDvbBf
```

**Comment by tomhughes** [comment]
As with #1 this has absolutely nothing to do with this repository, which contains th skin used on http://wiki.osmfoundation.org/ and has nothing to do with http://wiki.openstreetmap.org/ at all.
