### ISSUE TITLE
Move to osmfoundation organization

### ISSUE THREAD

**Issue by nebulon42** [openstreetmap/mediawiki-skins-osmf#3]
I think it might be appropriate to move this repository to the osmfoundation organization.

**Comment by tomhughes** [comment]
Are you actually asking on behalf of the foundation or is just a random observation?

I'm happy to move it but I'm not an admin there so it probably needs somebody who is to assist, and the chef recipes will need updating to match.

**Comment by nebulon42** [comment]
Actually neither. :)
I try to start doing some work for CWG, but have not formally joined yet (if something like that is possible). One thing I want try to do is refreshing the osmfoundation skin a bit. Via the chef repo I found this repo and since there is also the osmfoundation organization I thought this might be a more appropriate place for this. But this is just a minor thing for me.

Thanks for your quick response. I will bring this up on the next CWG meeting and see if and how we could get this going.

**Comment by nebulon42** [comment]
I had to start from scratch (or more specifically from Vector) for becoming responsive, so I think moving is no longer an option as this skin might get obsolete IF the other skin is chosen.

See also https://github.com/gmgeo/osmf-mediawiki-skin.
